# Generated by Django 6.0.5 on 2026-05-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('last_bell', models.DateTimeField(blank=True, null=True)),
                ('bell_required', models.BooleanField(default=False)),
                ('total_seconds', models.IntegerField(default=0)),
                ('last_cycle', models.IntegerField(default=0)),
            ],
        ),
    ]
