# Generated by Django 6.0.5 on 2026-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='last_reset',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='duty',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
